apiVersion: v1
kind: Service
metadata:
  name: jokesapi-wf
  namespace: jokesapi-ns
spec:
  type: LoadBalancer
  selector:
    app: jokesapi-wf
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000