apiVersion: v1
kind: Service
metadata:
  name: jokesapi-workflow
  namespace: namespace-workflow-1710913384229
spec:
  type: LoadBalancer
  selector:
    app: jokesapi-workflow
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000