apiVersion: v1
kind: Service
metadata:
  name: exchange-wf
  namespace: exchange-ns
spec:
  type: LoadBalancer
  selector:
    app: exchange-wf
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000